<?php
/**
 * @file
 * Code for the Urbinfo search feature.
 */

include_once 'urbinfo_search.features.inc';

/**
 * Implements hook_preprocess_views_views_json_style_simple().
 *
 * Add pager data to JSON response.
 */
function urbinfo_search_preprocess_views_views_json_style_simple(&$vars) {
  global $pager_total, $pager_page_array, $pager_total_items, $pager_limits;
  $vars['rows']['pager'] = array(
    'pages' => $pager_total[0],
    'page' => $pager_page_array[0] + 1,
    'count' => intval($pager_total_items[0]),
    'limit' => intval($pager_limits[0])
  );

  $results = $vars['view']->query->getSearchApiResults();
  if (isset($results['search_api_facets']['field_facilities'])) {
    foreach ($results['search_api_facets']['field_facilities'] as $facet) {
      $vars['rows']['facets']['field_facilities'][trim($facet['filter'], '"')] = $facet['count'];
    }
  }
  else {
    $vars['rows']['facets']['field_facilities'] = array();
  }
}
