---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04-nochef
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.6.0
    network:
      - ["private_network", {ip: "11.12.14.14"}]
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[hipsnip-jetty_test::default]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/default_test.rb"
- name: jetty-9
  run_list:
    - recipe[hipsnip-jetty_test::jetty_9]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/jetty_9_test.rb"
- name: jetty-8
  run_list:
    - recipe[hipsnip-jetty_test::jetty_8]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/jetty_8_test.rb"
- name: logging-on-files
  run_list:
    - recipe[hipsnip-jetty_test::logging_on_files]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/logging_on_files_test.rb"
- name: use-syslog-jetty-9
  run_list:
    - recipe[hipsnip-jetty_test::use_syslog_jetty_9]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/use_syslog_jetty_9_test.rb"
- name: use-syslog-jetty-8
  run_list:
    - recipe[hipsnip-jetty_test::use_syslog_jetty_8]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/use_syslog_jetty_8_test.rb"
- name: custom-start-ini
  run_list:
    - recipe[hipsnip-jetty_test::custom_start_ini]
    - recipe[minitest-handler]
  attributes:
    minitest:
      tests: "hipsnip-jetty_test/custom_start_ini_test.rb"