source 'https://rubygems.org'

group :development do

  # Sass, Compass and extensions.
  #
  gem 'sass', '3.4.5'             # Sass.
  gem 'sass-globbing', '1.1.1'    # Import Sass files based on globbing pattern.
  gem 'compass', '1.0.1'          # Framework built on Sass.
  gem 'oily_png', '1.1.2'         # Faster Compass sprite generation.
  gem 'bootstrap-sass', '3.2.0.2' # Sass port of Bootstrap CSS framework.

end
